name: chatgpt2api-code-test

services:
  app:
    image: ghcr.io/basketikun/chatgpt2api:latest
    container_name: chatgpt2api-code-test
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - ./api:/app/api
      - ./services:/app/services
      - ./utils:/app/utils
      - ./main.py:/app/main.py
      - ./VERSION:/app/VERSION
      - ./web/out:/app/web_dist
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - STORAGE_BACKEND=json
      - CHATGPT2API_AUTH_KEY=carmin123456
